spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webtoon?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

---
spring:
  profiles: test
  h2:
    console:
      enabled: true


