spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webtoon?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

---
spring:
  profiles: test
  h2:
    console:
      enabled: true