spring:
  profiles:
    active: local

---
spring:
  profiles: local
  h2:
    console:
      enabled: true

  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false

---

